### ISSUE TITLE
レポジトリをwatnowでなく誰か保有のものに移行する

### ISSUE THREAD

**Issue by YukaChoco** [YukaChoco/project-who#78]
### 作業ファイル

特になし

### 必要な作業内容

```bash
1.新たなレポジトリを作成する
2.本レポジトリを移す
3.Vercelにデプロイする
```

### 理由

本レポジトリのままだと、Netlifyにしかデプロイできず、コミットごとのデプロイが出来ないから。
新たに作成してVercelにデプロイし直すことで、PRごとに簡単にデバッグが行える。

### 補足

11/13のリリース時にVercelでデプロイしたい。

**Comment by mercy34mercy** [comment]
@YukaChoco 
Closeしときー
