### ISSUE TITLE
firebaseの秘匿情報をenv化

### ISSUE THREAD

**Issue by mercy34mercy** [YukaChoco/project-who#91]
### 作業ファイル

firebase.js

### 必要な作業内容

```bash
1. .envを作成
2. .gitignoreで.envをgit管理から除外
3. firebaseの秘匿情報を再作成
4. .envに秘匿情報を記載
5. dotenvで.envから秘匿情報を読み取って、firebaseインスタンスを初期化
```

### 理由

publicレポジトリなので、秘匿情報があると誰でも自由にfirebaseの情報をいじれちゃう
秘匿情報を再度生成しないと、せっかくenv化しても意味ないので注意！

**Comment by YukaChoco** [comment]
@mercy34mercy これ自分が蒔いた種なので自分で回収させてください

**Comment by mercy34mercy** [comment]
よろりんこー
